### ISSUE TITLE
引用之后报错

### ISSUE THREAD

**Issue by PDR-SY** [cjhandroid/TrimmerVideoView#2]
Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.cjh.videotrimmerlibrary.VideoTrimmerView 

Caused by: java.lang.IllegalStateException: findViewById(R.id.recyclerView) must not be null
        at com.cjh.videotrimmerlibrary.VideoTrimmerView.getRecyclerView(VideoTrimmerView.kt:62)
        at com.cjh.videotrimmerlibrary.VideoTrimmerView.<init>(VideoTrimmerView.kt:36)
        at com.cjh.videotrimmerlibrary.VideoTrimmerView.<init>(VideoTrimmerView.kt:32)

**Comment by PDR-SY** [comment]
找到问题了，我有一个layout和video_trimmer_view命名一模一样，所以就一直null
